openapi: 3.2.0
info:
  title: Vantage Ping API
  description: The Vantage API provides programmatic access to the Vantage cloud cost management and FinOps platform.
  termsOfService: https://www.vantage.sh/terms-of-use
  contact:
    name: Vantage Support
    url: https://www.vantage.sh
    email: support@vantage.sh
  version: 2.0.0
servers:
- url: https://api.vantage.sh/v2
security:
- oauth2:
  - read
tags:
- name: Ping
  description: Operations about Pings
paths:
  /ping:
    get:
      tags:
      - Ping
      description: This is a health check endpoint that can be used to determine Vantage API healthiness. It will return 200 if everything is running smoothly.
      operationId: ping
      responses:
        '200':
          description: This is a health check endpoint that can be used to determine Vantage API healthiness. It will return 200 if everything is running smoothly.
          content: {}
      security:
      - oauth2:
        - read
      summary: Ping
      x-summary-source: derived
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://console.vantage.sh/account/profile
          scopes:
            read: Grants read access
            write: Grants write access
x-original-swagger-version: '2.0'
